### ISSUE TITLE
Can't add key to OVH account

### ISSUE THREAD

**Issue by JonahAragon** [kryptco/kr-u2f#18]
Trying to add a security key to my OVH.com account in Chrome with the extension installed shows a `Can not find your security key` error.

![image](https://user-images.githubusercontent.com/3637842/47608865-3770f080-d9fa-11e8-86bf-53b4f01dbf63.png)

**Comment by agrinman** [comment]
@JonahAragon we're working on releasing a fix for this shortly, thanks for reporting!

**Comment by kcking** [comment]
This actually seems to be a bug on OVH's end. Trying to register a yubikey with Chrome shows the same message.

Specifically, the appId requested by OVH is `https://www.ovhcloud.com/u2f/appIds.json`, but this URL does not return a valid trusted_facets JSON file. Instead of redirecting to `https://us.ovhcloud.com`, `https://www.ovhcloud.com/u2f/appIds.json` should probably serve the same thing as `https://us.ovhcloud.com/u2f/appIds.json`.

I don't have connections to anyone at OVH but happy to help them fix this issue.

**Comment by kcking** [comment]
What I said above only applies to `us.ovhcloud.com`. We have released an update to fix this bug on `ca.ovhcloud.com`. Please let us know if you're still having issues.

**Comment by mpalczynski** [comment]
Have you deployed fix to all locations? I'm from EU and have same issue here. Wanted to create a ticket and report that but the service desk is useless. I can't create custom ticket.

**Comment by fascoli** [comment]
same problem here - tried with multiple browsers, but I can't add a YubiKey to my account
