### ISSUE TITLE
Violate the web store policy

### ISSUE THREAD

**Issue by akakou** [kryptco/kr-u2f#67]
I found the alert that says `this extension violates the web store policy.`,
and the kryptonite authenticator extension was removed from the web store.

Is it the situation operators expected?

![image](https://user-images.githubusercontent.com/22659592/177028640-7f8e86c4-a35e-4ba7-a5bd-b00052f9ac73.png)

**Comment by Ewarren7** [comment]
@akakou I reached out to co founder on Twitter and he said it was because they never updated it to manifest v3 which google is now requiring. If you weren't aware akamai bought this company and only develops the paid version now. So fortunately nothing malicious. 

You can keep using it if you manually install it from this repo.

**Comment by akakou** [comment]
Thank you!
